version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  target-branch: "hibernate6"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
      - "sdou"

- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "hibernate6"
  schedule:
    interval: "daily"
