# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
    nightly-build:
      uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
      with:
        nightly: true
        java: '[17, 21]'
        os: '["ubuntu-latest"]'
      secrets: inherit

    hibernate-test:
      name: Test Hibernate ${{ matrix.hibernate }}
      needs: nightly-build
      runs-on: ubuntu-latest
  
      strategy:
        fail-fast: false
        matrix:
          hibernate: ["7.1.16.Final", "7.2.4.Final" ]
  
      steps:
        - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  
        - name: Set up JDK
          uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
          with:
            java-version: 17
            distribution: 'temurin'
            cache: 'maven'
  
        - name: Run Compatibility Tests
          run: mvn -B jacoco:prepare-agent surefire:test -Dhibernate.version=${{ matrix.hibernate }}
  
        - name: Run Tests
          run: mvn -B jacoco:prepare-agent surefire:test
  
        - name: Archive Test Results
          if: ${{ always() }}
          uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
          with:
            name: test-reports-hibernate-${{ matrix.hibernate }}
            path: |
              **/target/surefire-reports
              **/target/jacoco.exec