name: 'Continuous Integration - Report'
on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]

  workflow_dispatch:

jobs:
  test-report:
    name: Report Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/test-reports-*/**/*.xml"
